/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import frc.robot.Constants;

import static edu.wpi.first.units.Units.*;

import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.MotionMagicTorqueCurrentFOC;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.ForwardLimitSourceValue;
import com.ctre.phoenix6.signals.ForwardLimitTypeValue;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.signals.ReverseLimitSourceValue;
import com.ctre.phoenix6.signals.ReverseLimitTypeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.ElevatorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;

public class Climber extends SubsystemBase {
    /** Position setpoints for the climber elevator. */
    public enum Setpoint {
        Reach(Rotations.of(Constants.ClimberConstants.kClimberReachSetpoint)),
        PullDown(Rotations.of(Constants.ClimberConstants.kClimberPullDownSetpoint)),
        YButton(Rotations.of(Constants.ClimberConstants.kClimberYButtonSetpoint));

        /** The position target of the setpoint in angular units. */
        public final Angle target;
        /** The position target of the setpoint in linear units. */
        public final Distance targetDist;

        private Setpoint(Angle target) {
            this.target = target;
            this.targetDist = kDrumRadius.times(target.in(Radians));
        }
        private Setpoint(Distance target) {
            this.target = Radians.of(target.div(kDrumRadius).magnitude());
            this.targetDist = target;
        }
    }

    private static final int kNumConfigAttempts = 2;

    private static final double kGearRatio = Constants.ClimberConstants.kSensorToMechanismRatio;
    private static final Distance kDrumRadius = Meters.of(0.0254);
    private static final Distance kMaxHeight = Meters.of(0.75);

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("Rio");     //change to Rio once on actual robot
    private final TalonFX leadClimberMotor = new TalonFX(Constants.ClimberConstants.kClimberMotorID, kCANBus);

    /* device status signals */
    private final StatusSignal<Angle> leadClimberMotorPosition = leadClimberMotor.getPosition(false);
    private final StatusSignal<AngularVelocity> leadClimberMotorVelocity = leadClimberMotor.getVelocity(false);
    private final StatusSignal<Current> leadClimberMotorTorqueCurrent = leadClimberMotor.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final MotionMagicTorqueCurrentFOC setpointRequest = new MotionMagicTorqueCurrentFOC(0);
    private final DutyCycleOut manualRequest = new DutyCycleOut(0);
    private final DutyCycleOut calibrationRequest = new DutyCycleOut(-0.1)
        .withIgnoreHardwareLimits(true)
        .withIgnoreSoftwareLimits(true);

    /** Trigger to detect when the elevator drives into a hard stop. */
    public final Trigger isHardStop = new Trigger(() -> {
        return leadClimberMotorVelocity.getValue().abs(RotationsPerSecond) < 1 &&
            leadClimberMotorTorqueCurrent.getValue().abs(Amps) > 10;
    }).debounce(0.1);

    /* simulation */
    private final ElevatorSim leadClimberMotorSim = new ElevatorSim(
        DCMotor.getKrakenX60Foc(1),
        kGearRatio, 5, kDrumRadius.in(Meters),
        0.0, kMaxHeight.in(Meters), true, 0.0
    );

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization of the elevator */
    private final Mechanism2d mech2d = new Mechanism2d(1, kMaxHeight.in(Meters));
    private final MechanismLigament2d leadClimberMotorMech2d = mech2d.getRoot("leadClimberMotor Root", 0.500, 0)
        .append(new MechanismLigament2d("leadClimberMotor", leadClimberMotorSim.getPositionMeters(), 90));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

    /** Configs common across just the leader motors. */
    private static final TalonFXConfiguration leaderInitialConfigs = motorInitialConfigs.clone();

    /** Configs for {@link #leadClimberMotor}. */
    private final TalonFXConfiguration climberMotorConfigs = leaderInitialConfigs.clone()
        .withMotorOutput(
            leaderInitialConfigs.MotorOutput.clone()
                .withNeutralMode(NeutralModeValue.Brake)//coast mode changed to brake 3/7/26
        )
        .withCurrentLimits(
            leaderInitialConfigs.CurrentLimits.clone()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        )
        .withSlot0(
            leaderInitialConfigs.Slot0.clone()
                .withKP(50) // 100 // 50
                .withKI(0.001) // 0
                .withKD(0)
                .withKS(0.2)
                .withKV(0.12)
                .withKA(0)
                .withKG(0)
                .withGravityType(GravityTypeValue.Elevator_Static)
        )
        .withFeedback(
            leaderInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(kGearRatio)
        )
        .withHardwareLimitSwitch(
            leaderInitialConfigs.HardwareLimitSwitch.clone()
                .withForwardLimitEnable(true)
                .withForwardLimitAutosetPositionEnable(false)
                .withForwardLimitRemoteSensorID(0)
                .withForwardLimitSource(ForwardLimitSourceValue.LimitSwitchPin)
                .withForwardLimitType(ForwardLimitTypeValue.NormallyOpen)
                .withReverseLimitAutosetPositionEnable(false)
                .withReverseLimitEnable(true)
                .withReverseLimitRemoteSensorID(0)
                .withReverseLimitSource(ReverseLimitSourceValue.LimitSwitchPin)
                .withReverseLimitType(ReverseLimitTypeValue.NormallyOpen)
        )
        .withMotionMagic(
            leaderInitialConfigs.MotionMagic.clone()
                .withMotionMagicCruiseVelocity(RotationsPerSecond.of(30)) //30
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(30)) //30
                .withMotionMagicJerk(RotationsPerSecondPerSecond.per(Second).of(10)) //10
        )
        .withSoftwareLimitSwitch(
            leaderInitialConfigs.SoftwareLimitSwitch.clone()
                .withReverseSoftLimitEnable(true)
                .withReverseSoftLimitThreshold(Rotations.of(Constants.ClimberConstants.kClimberReverseSoftLimit))
                .withForwardSoftLimitEnable(true)
                .withForwardSoftLimitThreshold(Rotations.of(0))
        );

    public Climber() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = leadClimberMotor.getConfigurator().apply(climberMotorConfigs);
            if (status.isOK()) break;
        }


        /* set the default command to neutral output */
        setDefaultCommand(manualDrive(() -> 0.0));
        /* alternatively, the default command can hold position */
        // setDefaultCommand(holdPosition());

        SmartDashboard.putData("Climber", mech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The Position of the elevator
     */
    public Angle getPosition() {
        return leadClimberMotorPosition.getValue();
    }

    /**
     * @return The Velocity of the elevator
     */
    public AngularVelocity getVelocity() {
        return leadClimberMotorVelocity.getValue();
    }

    /**
     * @return The TorqueCurrent of the elevator
     */
    public Current getTorqueCurrent() {
        return leadClimberMotorTorqueCurrent.getValue();
    }

    /**
     * Holds the elevator at the current position using PID.
     *
     * @return Command to run
     */
    public Command holdPosition() {
        return runOnce(() ->
            setpointRequest.withPosition(leadClimberMotorPosition.getValue())
        ).andThen(run(() -> {
            leadClimberMotor.setControl(setpointRequest);
        }));
    }

    /**
     * Drives the elevator to the provided position setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command goToSetpoint(Supplier<Setpoint> setpoint) {
        return run(() -> {
            setpointRequest.withPosition(setpoint.get().target);
            leadClimberMotor.setControl(setpointRequest);
        });
    }

    /**
     * Manually drives the elevator with the provided duty cycle output.
     *
     * @param manualOutput Function returning the duty cycle to apply
     * @return Command to run
     */
    public Command manualDrive(DoubleSupplier manualOutput) {
        return run(() -> {
            manualRequest.withOutput(manualOutput.getAsDouble());
            leadClimberMotor.setControl(manualRequest);
        });
    }

    /**
     * Recalibrates the elevator zero point. This slowly drives the elevator
     * down until we see a drop in velocity and a spike in stator current,
     * indicating that we've hit a hard stop.
     *
     * @return Command to run
     */
    public Command calibrateZero() {
        return run(() -> {
            leadClimberMotor.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0).withTimeout(0.25)
                .finallyDo(() -> {
                    leadClimberMotor.setPosition(Rotations.of(0));
                })
        );
    }

    @Override
    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            leadClimberMotorPosition,
            leadClimberMotorVelocity,
            leadClimberMotorTorqueCurrent
        );

        leadClimberMotorMech2d.setLength(
            leadClimberMotorPosition.getValueAsDouble() * kDrumRadius.in(Meters) * 2 * Math.PI
        );
    }

    private void startSimThread() {
        leadClimberMotor.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        leadClimberMotor.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var climberMotorSimState = leadClimberMotor.getSimState();

            /* First set the supply voltage of all the devices */
            climberMotorSimState.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new position and velocity of the simulated elevator */
            leadClimberMotorSim.setInputVoltage(climberMotorSimState.getMotorVoltage());
            leadClimberMotorSim.update(deltaTime);

            /* Apply the new rotor position and velocity to the motors (before gear ratio) */
            climberMotorSimState.setRawRotorPosition(
                Radians.of(leadClimberMotorSim.getPositionMeters() / kDrumRadius.in(Meters) * kGearRatio)
            );
            climberMotorSimState.setRotorVelocity(
                RadiansPerSecond.of(leadClimberMotorSim.getVelocityMetersPerSecond() / kDrumRadius.in(Meters) * kGearRatio)
            );
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }
}

